### ISSUE TITLE
Question about codeblock

### ISSUE THREAD

**Issue by mconsidine** [Vdesnoux/Solex_ser_recon#13]
Hi,
I have a question about the following block of code in Inti_recon.py:
`# creation du tableau d'indice des lignes a corriger
    l_col=np.where(hcol!=0)
    listcol=l_col[0]
    

    # correction de lignes par filtrage median 13 lignes, empririque
    for c in listcol:
        m=img[c-7:c+6,]
        s=np.median(m,0)
        img[c-1:c,]=s`

It is the loop I am wondering about.  Let's say that "c" is 10 at some point.  So "m"  refers to img[3:16.] and then a median of this is calculated along axis=0, if I understand correctly.

Then, the section in img referred to by [9:10,] is replaced by this median.

When the loop advances to 11, "m" refers to img[4:17,] and a median is calculated again.

However, that median now includes in it the results of the median calculation when c was 10, as that result was copied back to "img", rather than a copy of "img".

Do I understand this correctly?  It would seem to me that would not be an intended outcome, but if so I would be interested in the logic behind it.

Thank you,
Matt

**Comment by Vdesnoux** [comment]
Hi Matt
You are right - I noticed that and try to detect if consecutive lines but failed and let it that way. Now at that time i did not know about the difference of behavior between newimg=img and newimg=np.copy(img)... so no logic
what about 
refimg=np.copy(img)
then 
m=refimg[c-7:c+6,]

**Comment by mconsidine** [comment]
Yes, I think that is all that is needed.  Store the changes in a copy then
replace img with the copy.
Matt
