### ISSUE TITLE
poly error?

### ISSUE THREAD

**Issue by mconsidine** [Vdesnoux/Solex_ser_recon#16]
In running v3.2.2 from command line in Ubuntu, with python 3.8, I get

$ python3 Inti_ser_recon.py
Traceback (most recent call last):
  File "Inti_ser_recon.py", line 344, in <module>
    poly.append(float(my_dictini['poly_slit_a']))
KeyError: 'poly_slit_a'

This comes about if the inti.yaml file is present from the github download.  Ie, in a new install it doesn't get overwritten, so when the code looks to select poly_slit_a, it doesn't exist yet...

Matt

**Comment by Vdesnoux** [comment]
I removed the inti.yaml from the distribution. But yes, for new version installation always remove the inti.yaml to create it with the new expected format
