### ISSUE TITLE
yaml issues

### ISSUE THREAD

**Issue by thelondonsmiths** [Vdesnoux/Solex_ser_recon#17]
Hi Valerie, I just downloaded both the Python code and the Windows version. There are some minor issues with the GitHub version.

-- The requirements should be updated to include 'pyyaml' (i.e. 'pip install pyyaml')
-- The README Requirements should be updated to include both 'serfilesreader' and 'pyyaml'
-- The included 'inti.yaml' file does not run correctly (it presumably has some missing data). In fact, if the file does not exist, the program creates a new one which does work. So best to not include the 'inti.yaml' in the repository.
-- Minor spelling corrections in the English version: in 'Inti_recon', 'Width and Height of SER frames' (instead of 'Wide and Heiht') and below that, 'Number of frames' (instead of 'Frames number').

By the way, I notice your version generally does better with H-alpha and my version works better on Calcium. I'm not sure why exactly.

**Comment by Vdesnoux** [comment]
Thanks ! I will remove the inti.yaml and add the requirements you listed, thank you
(and the spelling...)
If I remember on calcium you compute the disk not from the line center with poor intensity but you applied a small shift to have more signal.
