### ISSUE TITLE
Bandwidth of the image

### ISSUE THREAD

**Issue by thelondonsmiths** [Vdesnoux/Solex_ser_recon#2]
Hi Valerie,
How does the "bandwidth" work in your program? Is there a default pixel width used and can this be changed? For example, I can understand that at H-alpha, you probably want the minimum bandwidth which the SolEx can provide. But in Calcium, a much wider bandwidth is sufficient and may even be desirable.
Thanks.

**Comment by Vdesnoux** [comment]
Hi
Yes we use here only one pixel to have the best monochromatic image. Regarding calcium, as you suggested, can be interesting to sum 3 or 3 pixels around. It will decrease the bandwidth but may increase the intensity. I guess someting to test...
