### ISSUE TITLE
Improvement for prom image

### ISSUE THREAD

**Issue by mconsidine** [Vdesnoux/Solex_ser_recon#3]
Hi Vdesnoux/thelondonsmiths,

I'm seemingly not able to fork thelondonsmiths version of the main code, so that I can upload my own tweak.  So I'm posting this here and apologize if there's a better way to approach this.

Bottom line : in creating the prom/protus image, I believe it makes sense to cut the disc of the sun out first, and then rebalance/process the result.  I attach here the relevant change to thelondonsmiths SHG_MAIN.py, for lines 278-306.  I've added comments (in English ... sorry!)  that I hope make the idea clear.

Mconsidine
`
        #image seuils protus
        frame1=np.copy(frame)
        #MattC cut out disk first
        #MattC BTW given default setting of disk_display this was never executed
        #if ratio_fixe==0 and disk_display==True:
        #MattC for now, let's always do this
        if 1==1 :
            #MattC - demo simple processing of proms seperate from disc settings
            clahe2 = cv2.createCLAHE(clipLimit=1.0, tileGridSize=(1,1))
            cl2 = clahe2.apply(frame1)
            x0=cercle[0]
            y0=cercle[1]-1
            r=int(cercle[2]*0.5)+1
            #MattC - turn disc to black, more aesthetically pleasing, IMHO
            frame1=cv2.circle(cl2, (x0,y0),r,0,-1)
        #MattC adjust scaling
        Seuil_haut=np.percentile(frame1,99.9999)
        Seuil_bas=0
        print('seuil bas protu', Seuil_bas)
        print('seuil haut protu', Seuil_haut)
        frame1[frame1>Seuil_haut]=Seuil_haut
        fc2=(frame1-Seuil_bas)* (65000/(Seuil_haut-Seuil_bas))
        fc2[fc2<0]=0
        frame_contrasted3=np.array(fc2, dtype='uint16')
        #MattC code that was at this line moved up above ...
        if flag_result_show:
            cv2.imshow('sun3',frame_contrasted3)
            #cv2.waitKey(0)

`

**Comment by Vdesnoux** [comment]
Hi Matt
I added a disk in the new version, and fixed a bug on the thresholding. Lett's see if it meets the expectations...

**Comment by mconsidine** [comment]
Hi,
I'm attaching here a comparison of the the prom results, one being what I think is the current way in Solex_ser_recon and the other reflects the adjustment I suggested above.  "16_33_15_pipp_protus.png" is the new version ...

The relevant portion of code that generated this is
`   #prom image thresholds
    if disk_display==True:
        x0=circle[0]
        y0=circle[1]
        wi=circle[2]-5
        he=circle[3]-5
        #ang=-int(circle[3])
        r=int(min(wi,he)-3)
        c=(0,0,0)
        #r=int(circle[2])-5
        #frame_contrasted3=cv2.circle(frame_contrasted3, (x0,y0),r,80,-1,lineType=cv2.LINE_AA)
        frame=cv2.ellipse(frame, (x0,y0),(wi,he),-circle[4],0,360,(0,0,0),-1,lineType=cv2.LINE_AA ) #MattC apply tilt, change color to black
    frame1=np.copy(frame)
    Threshold_Upper=np.percentile(frame1,99.9999) #MattC drop *.18
    Threshold_low=0
    #print('Threshold Lower prom', Threshold_low)
    #print('Threshold Upper prom', Threshold_Upper)
    frame1[frame1>Threshold_Upper]=Threshold_Upper
    fc2=(frame1-Threshold_low)* (scalemax/(Threshold_Upper-Threshold_low))
    fc2[fc2<0]=0
    frame_contrasted3=np.array(fc2, dtype=datasize)
    cv2.imshow('proms',frame_contrasted3)`

(Apologies for supply an English-language version.  But it should be easy to see that I just moved one block of code further up and made a couple of small adjustments reflected by my initials).

To my eye, the result seems better when I compare them side by side in GIMP, for instance.

I hope this helps!
![16_33_15_pipp_protus](https://user-images.githubusercontent.com/586812/126568393-0ac95d41-42ac-4aa4-9017-a2ad897a5c95.png)
![16_33_15_pippold_protus](https://user-images.githubusercontent.com/586812/126568395-6d2d8d69-0046-44ab-abfa-0665915cb2d3.png)

**Comment by Vdesnoux** [comment]
I modified the code as per your suggestion, but sill keep some threshold high. So, done !
