### ISSUE TITLE
Issue with edited SER files

### ISSUE THREAD

**Issue by thelondonsmiths** [Vdesnoux/Solex_ser_recon#4]
Dear V, I noticed this edge case in this version and also the previous one. If one takes data with multiple scans, then the best way to process them in an automated way is to crop them into two (or more) pieces. The easiest is to use SER Player (but I assume PIPP will work also). The problem is in the editing process some header bytes must get lost and the program will crash because it can't find them. We were able to make your program work on edited files by commenting out 3 lines (see attached figure, Observer, Instrument, Telescope). In our version, we did not see the need for these segments of code so left them out. D&A.

![ser reader bytes](https://user-images.githubusercontent.com/13508665/126082489-19f7241b-8bea-470a-8ba0-fe8414235620.JPG)

**Comment by Vdesnoux** [comment]
I now use the serfilesreader module  from JB Butet. I wish I could use the informations like telescope but unfortunatly this is not editable at acquisition in sharcap. So no usage for those 3 data...
