### ISSUE TITLE
A few issues with ellipse

### ISSUE THREAD

**Issue by thelondonsmiths** [Vdesnoux/Solex_ser_recon#5]
The new ellipse feature is very nice but does fail sometimes. I have tracked down how it fails but did not find where in the code the issue is yet. First of all, I notice that the .txt file does not save the SY/SX ellipse parameter when in automatic mode. This is information that probably should be saved to the .txt file. But I could read the SY/SX data on the console.

When the ellipse function fails, for some reason it performs the Y/X function but then does not do the tilt angle function. But I could take the SY/SX parameter as printed on the console, rerun the program, and manually enter the SY/SX number. With this convoluted method, it would produce the correct circular image! See below for console screenshots in the "fail" in auto mode then the "success" with the manual input of the SY/SX parameter. The data is the one I mentioned in my post on solex-project (data from http://www.astrosurf.com/solex/download/16_33_15.zip).

![logfile](https://user-images.githubusercontent.com/13508665/126084162-b974731d-650a-4fa1-a5b0-2316c2346420.JPG)

![logfile 2](https://user-images.githubusercontent.com/13508665/126084165-855e0ab7-03cc-42a1-b076-effd59abcfe1.JPG)

**Comment by mconsidine** [comment]
Out of curiosity, is there a reason to not use the openvision ellipse, fitEllipse, findContours, etc functions?

**Comment by Vdesnoux** [comment]
It shall be ok with the new version pasted 11 of august.
To Matt: no reason besides lack of knowledge and I think Doug and Andrew did explore interesting alternatives
