### ISSUE TITLE
Tilt correction not applied

### ISSUE THREAD

**Issue by mconsidine** [Vdesnoux/Solex_ser_recon#7]
Hi,
When I run the Solex_ser_recon code on the 16_33_15.ser file from the Solex site, the tilt correction is not applied.  When I upload it to Inti, it is.

It turns out line 1073 here of Inti_recon.py has a two part condition that needs to be met, whereas the code in Inti (which has the correct output) looks like this:
  if flag_nobords==False:

Perhaps an edit/update didn't get transferred to the Solex_ser_recon code?
Matt

**Comment by Vdesnoux** [comment]
yes, shall be fixed now - thanks
