### ISSUE TITLE
Ellipse fitting question

### ISSUE THREAD

**Issue by mconsidine** [Vdesnoux/Solex_ser_recon#9]
Hi Valerie (and anyone else watching),
I have run into a "weirdness" that I can't correct for and thought you or someone else could shed some light on the problem.

I have a scan sequence that is "backwards" from the way the sun was projected on the slit and I figured that it would be easy enough to correct by flipping the "Disk" image and then continuing on with the processing.  The reconstruction comes out well without this, but is just reversed.
I expected that flipping the input to the ellipse routine would generate essentially the same result but with the correct orientation.  But that is not the case, it comes out distorted.

Do you have any suggestions as to why this would be the case?  I've been wrestling all day with it and have gotten nowhere.  I thought it might be some problem I introduced into my coce, but I just pulled down DJIBB's version, changed the one line to flip the Disk horizontally, and I get the exact same outcome.

Thanks for any thoughts,
Matt

**Comment by Vdesnoux** [comment]
Well, i would process it without flipping and just flip the final _recon.fits image...
I know, it does not really answer your question :) be carefull, previous version (before 11 august) was not really using ellipse fitting correctly but I would be like you, expecting the same result.

**Comment by mconsidine** [comment]
I will check.  Thank you.
Matt
